#!/bin/bash
source ./test_srcs/colors.sh
#source ./test_srcs/func_list.sh
source ./test_srcs/options.sh
DIRECTORY=$(cd `dirname $0` && pwd)
PWD=${pwd}
OWNER=$(sed -n '6p' Makefile | cut -d ' ' -f6)
MAKEFILE_PATH=${pwd}Makefile
#OPTIONS
RM_TEST_DIR=1
TEST_P1=1
TEST_P2=1
TEST_BONUS=1
for OPTION in "$@"
do
	case "${OPTION}" in
		"-p1")				TEST_P1=1
			TEST_P2=0
			TEST_BONUS=0 ;;
		"-p2")				TEST_P1=0
			TEST_P2=1
			TEST_BONUS=0 ;;
		"-b")				TEST_P1=0
			TEST_P2=0
			TEST_BONUS=1 ;;
		"-s")				RM_TEST_DIR=0 ;;
	esac
done
LIB_NAME=$(grep "libft.a" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w libft.a)
ALL_RULE=$(grep "all" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w all)
NAME_RULE=$(grep "\${NAME}" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w \${NAME})
CLEAN_RULE=$(grep "clean" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w clean)
FCLEAN_RULE=$(grep "fclean" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w fclean)
RE_RULE=$(grep "re" ${MAKEFILE_PATH} | tr -d ' ' | tr -d '\t' | cut -d ':' -f 1 | grep -w re)
printf ${BOLD}${RED}"  _         _   _            _               _      _ _ _      __ _          \n"
printf " | |    ___| |_( )___    ___| |__   ___  ___| | __ | (_) |__  / _| |_   __ _ \n"
printf " | |   / _ \ __|// __|  / __| '_ \ / _ \/ __| |/ / | | | '_ \| |_| __| / _\` | \n"
printf " | |__|  __/ |_  \__ \ | (__| | | |  __/ (__|   <  | | | |_) |  _| |_ | (_| |\n"
printf " |_____\___|\__| |___/  \___|_| |_|\___|\___|_|\_\ |_|_|_.__/|_|  \__(_)__,_|\n\n"
printf " ============================================================================\n"
printf ${WHITE}"\n"
#norminette_path()
#{
read -p "Do you run the test from Guacamole/42 Campus [Y/N]?" AT_42
if [[ "${AT42}" == "Y" ]];then
	NORMINETTE_PATH=/usr/share/norminette/norminette.rb
else
	NORMINETTE_PATH=~/.norminette/norminette.rb
#else
#	norminette_path
fi
#}

#Check for code owner / Makefile presence / and libft.h presence

printf ${BOLD}${BLUE}"\n ============================================================================\n"
printf " *				PROJECT CHECK				    *\n"
printf " ============================================================================\n\n"
printf ${WHITE}"\033[4GCode owner\033[30GMakefile\033[56GHeader\n"
#Check the username in every C files, if username not unique, check manually with the command below (paste only from for to done. Some students are even able to copy/paste header :v
if [[ "$(for i in srcs/*.c; do sed -n '6p' $i | tail -1 | cut -f5 -d ' '; done | uniq | wc -l | sed -e 's/^[ \t]*//')" == "1" ]]; then
	printf ${GREEN}"\033[4G${OWNER}"
else
	printf ${RED}"\033[4GMultiple names ! ✖"
fi
if [ -n "$(find ./ -type f -name "Makefile" -exec basename {} \;)" ];then
	printf ${GREEN}"\033[30G[OK]"
else
	printf ${RED}"\033[30G[KO]"
fi
if [ -n "$(find ./ -type f -name "libft.h" -exec basename {} \;)" ];then
	printf ${GREEN}"\033[56G[OK]\n"
else
	printf ${RED}"\033[56G[KO]\n"
fi

#Check for mandatory rules in the Makefile

printf ${BOLD}${BLUE}"\n ============================================================================\n"
printf " *				MAKEFILE CHECK				    *\n"
printf " ============================================================================\n\n"
printf ${WHITE}"\033[4G\${NAME}\033[17Gall\033[30Gclean\033[43Gfclean\033[56Gre\033[69Glibft.a\n"
if [[ "${NAME_RULE}" == *"\${NAME}"* ]]; then 
	printf ${GREEN}"\033[4G[OK]"
else
	printf ${RED}"\033[4G[KO]"
fi
if [[ "${ALL_RULE}" == *"all"* ]]; then 
	printf ${GREEN}"\033[17G[OK]"
else
	printf ${RED}"\033[17G[KO]"
fi
if [[ "${CLEAN_RULE}" == *"clean"* ]]; then 
	printf ${GREEN}"\033[30G[OK]"
else
	printf ${RED}"\033[30G[KO]"
fi
if [[ "${FCLEAN_RULE}" == *"fclean"* ]]; then 
	printf ${GREEN}"\033[43G[OK]"
else
	printf ${RED}"\033[43G[KO]"
fi
if [[ "${RE_RULE}" == *"re"* ]]; then 
	printf ${GREEN}"\033[56G[OK]"
else
	printf ${RED}"\033[56G[KO]"
fi
if [[ "${LIB_NAME}" == *"libft.a"* ]]; then 
	printf ${GREEN}"\033[69G[OK]\n"
else
	printf ${RED}"\033[69G[KO]\n"
fi

#Check for Compilation / Flags error (-Wextra -Werror -Wall) / Norm error / Tests results

printf ${BOLD}${BLUE}"\n ============================================================================\n"
printf ${BOLD}${BLUE}" *				C FILES CHECK				    *\n"
printf ${BOLD}${BLUE}" ============================================================================\n\n"
printf ${WHITE}"\033[4GFunction\033[24GFlags/Compil\033[40GNorm\033[52GTests\n\n"

PART_1=(
	'ft_atoi.c'
	'ft_bzero.c'
	'ft_calloc.c'
	'ft_isalnum.c'
	'ft_isalpha.c'
	'ft_isascii.c'
	'ft_isdigit.c'
	'ft_isprint.c'
	'ft_memccpy.c'
	'ft_memchr.c'
	'ft_memcmp.c'
	'ft_memcpy.c'
	'ft_memmove.c'
	'ft_memset.c'
	'ft_strchr.c'
	'ft_strrchr.c'
	'ft_strdup.c'
	'ft_strlcat.c'
	'ft_strlcpy.c'
	'ft_strlen.c'
	'ft_strncmp.c'
	'ft_strnstr.c'
	'ft_tolower.c'
	'ft_toupper.c'
)
PART_2=(
	'ft_substr.c'
	'ft_strjoin.c'
	'ft_strtrim.c'
	'ft_split.c'
	'ft_itoa.c'
	'ft_strmapi.c'
	'ft_putchar_fd.c'
	'ft_putendl_fd.c'
	'ft_putnbr_fd.c'
	'ft_putstr_fd.c'
)
BONUS_0=(
	'ft_lstadd_back.c'
	'ft_lstadd_front.c'
	'ft_lstclear.c'
	'ft_lstdelone.c'
	'ft_lstiter.c'
	'ft_lstlast.c'
	'ft_lstmap.c'
	'ft_lstnew.c'
	'ft_lstsize.c'
)

#Verify if functions respect the norm, compile and pass the tests
function_breaker()
{
	local part="$1"
	local color="$2"
	shift
	shift 								#save 2 first argument in local variable then shift them to the left ($1 and $2 gets lost)
	local arr=("$@") 					#allowing me to use the array with the last argument
	printf ${color}"\033[31G${part}\n"
	for val in "${arr[@]}"; do
		printf ${color}"\033[4G${val}"
		if [[ -z $(gcc -Wextra -Werror -Wall ./srcs/${val} ./tests_functions/${val} libft.a 2>&1 | head -1) ]]; then
			printf ${GREEN}"\033[24G[OK]"
		else
			printf ${RED}"\033[24G[KO]"
		fi
		if [[ -z $(${NORMINETTE_PATH} ./srcs/${val} | grep "Error\|Warning") ]]; then
			printf ${GREEN}"\033[40G[OK]"
		else
			printf ${RED}"\033[40G[KO]"
		fi
		i=52
		test_num=1
		if test -f ./a.out; then
			./a.out > ./output/user/${val}
			while [ $i -le  70 ]; do
				if [[ -z $(diff ./output/expected/${val} ./output/user/${val} | grep ${test_num}c${test_num}) ]]; then
					printf ${GREEN}"\033[${i}G✔"
				else
					printf ${RED}"\033[${i}G✖"
				fi
				test_num=$(($test_num+1))
				i=$(($i+2))
			done
		else
			printf ${RED}"\033[${i}GCompil error\n"
			continue
		fi
		printf "\n"
	done
	printf "\n"
}

if [ ${TEST_P1} -eq 1 ]; then
	function_breaker "PART 1" ${CYAN} "${PART_1[@]}" 
fi
if [ ${TEST_P2} -eq 1 ]; then
	function_breaker "PART 2" ${CYAN} "${PART_2[@]}"
fi
if [ ${TEST_BONUS} -eq 1 ]; then
	function_breaker "BONUS" ${YELLOW} "${BONUS_0[@]}"
fi
